### PR TITLE
V2.0.1

### LINKED ISSUE #429: Add a cross (x) in the Import burrito dialog box
While importing a project with a burrito, if it fails to import then display a red cross in the checkbox on the dialog box.

### PR DESCRIPTION
**Pull request by Bobbykumar706584**
#411 point(2,3) dropdown responsive width fixed
#429 added cross and checkIcon in the import burrito

### CODE REVIEW

File: renderer/src/layouts/projects/ImportProjectPopUp.js [hunk 1]
```diff
@@ -12,6 +12,7 @@ import importBurrito, { viewBurrito } from '../../core/burrito/importBurrito';
 import * as logger from '../../logger';
 import ConfirmationModal from '../editor/ConfirmationModal';
 import { AutographaContext } from '@/components/context/AutographaContext';
+import { validate } from 'uuid';
```
Comment (RevantCI) [inline renderer/src/layouts/projects/ImportProjectPopUp.js:15]: This import can be removed

File: renderer/src/layouts/projects/ImportProjectPopUp.js [hunk 2]
```diff
@@ -186,7 +187,11 @@ export default function ImportProjectPopUp(props) {
                           className="w-full mb-4 bg-gray-200 block rounded shadow-sm sm:text-sm focus:border-primary border-gray-300"
                             type="text" value={sbData.burritoType} disabled />
                           <label className="inline-flex items-center">
-                            <input type="checkbox" className="form-checkbox" checked={sbData?.validate} disabled/>
+                            {(sbData?.validate)? 
+                            <CheckIcon className='w-6 h-6 text-green-500 border' />
+
+                            :<span className='w-6 h-6 text-red-500 text-center px-1 border'> X </span>
```
Comment (RevantCI) [inline renderer/src/layouts/projects/ImportProjectPopUp.js:193]: You can use XIcon

Comment (RevantCI) [reply renderer/src/layouts/projects/ImportProjectPopUp.js:193]: It can be combined with the logic below and written as 
<><XIcon className='w-6 h-6 text-red-500 border' /><span className="ml-2">Burrito validation Failed</span></>
You can remove the red text color as we have the red xicon

**Review by RevantCI — APPROVED** [review]
